# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Devops

variables:
 -myvar: $(my_var)

steps:
- script: |
    echo Hello, world!
    echo Welcome Jebin lets start the devops and learn
    echo my_var
  displayName: 'Run a multi-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
